title: Meadow Manual
email: your-email@example.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
markdown: kramdown
theme: null
layouts_dir: _layouts
data_dir: _data
baseurl: ""
url: "https://manual.meadow.space"
plugins:
  - jekyll-toc

defaults:
  - scope:
      path: ""
    values:
      toc: true