title: Meadow Manual
email: support@meadow.space
description: >- 
  Meadow is a social platform for building, publishing & distributing immersive content. This manual shows you how you can create and upload your own XR experiences.
markdown: kramdown
theme: null
layouts_dir: _layouts
include: ["pages"]
data_dir: _data
baseurl: ""
url: "https://manual.meadow.space"
permalink: /:title/
plugins:
  - jekyll-toc

defaults:
  - scope:
      path: ""
    values:
      toc: true
      description: "Meadow is a social platform for building, publishing & distributing immersive content. This manual shows you how you can create and upload your own XR experiences."