name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Specify the Ruby version

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: Build and deploy
        uses: helaili/jekyll-action@2.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
